---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-7
  run_list:
  - recipe[yum]
- name: centos-6.7
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list:
  - recipe[chef-solo-search]
  - recipe[users::sysadmins]
  - recipe[oh-my-zsh]
  attributes: {}
